### ISSUE TITLE
addRequestHandler override the default CefRequestHandler

### ISSUE THREAD

**Issue by KevinnZou** [DatL4g/KCEF#1]
As we discussed in this[ issue](https://github.com/KevinnZou/compose-webview-multiplatform/issues/37). `addRequestHandler` will override the default `CefRequestHandler` and block the future request.

**Comment by DatL4g** [comment]
8ebc5fee0281b52051474cb9ccbb645b71605852

**Comment by KevinnZou** [comment]
@DatL4g It appears that you just provided a default CefResourceRequestHandler, but the default CefRequestHandler is still missing. So should the same problem still exist if we just call addRequestHandler which will override the default implementation?

I have tested it with the latest KECF version and confirmed that the problem still exists. You can find the test code [here](https://github.com/KevinnZou/compose-webview-multiplatform/blob/34e4c6c846c8ab0281e17c8075aaeb4880ae6124/webview/src/desktopMain/kotlin/com/multiplatform/webview/web/WebEngineExt.kt#L174).

**Comment by KevinnZou** [comment]
> @DatL4g It appears that you just provided a default CefResourceRequestHandler, but the default CefRequestHandler is still missing. So should the same problem still exist if we just call addRequestHandler which will override the default implementation?
> 
> I have tested it with the latest KECF version and confirmed that the problem still exists. You can find the test code [here](https://github.com/KevinnZou/compose-webview-multiplatform/blob/34e4c6c846c8ab0281e17c8075aaeb4880ae6124/webview/src/desktopMain/kotlin/com/multiplatform/webview/web/WebEngineExt.kt#L174).

@DatL4g Are there any updates on this issue? We need to override onBeforeBrowse to intercept the Url request.
