### ISSUE TITLE
Cannot clone submodule

### ISSUE THREAD

**Issue by mgroth0** [DatL4g/KCEF#3]
I'd like to fork and potentially contribute to this library. However, it seems to depend on a submodule [here](https://github.com/DatL4g/KCEF/tree/master/jcef/src). When I tried to `git clone --recursive` I got an error for the submodule:

```txt
Please make sure you have the correct access rights
and the repository exists.
```

**Comment by DatL4g** [comment]
Make sure to setup SSH on your system correctly or just clone this module, edit the `.gitmodules` file to use http instead of ssh and then load the according submodule

**Comment by DatL4g** [comment]
Need to wait until https://github.com/JetBrains/jcef/pull/19 is merged
